galaxy_info:
  author: Juanjo Ponz
  description: Devops 
  company: Numenalia S.L

  license: license GPLv3

  min_ansible_version: 2.6.2

  platforms:
  - name: Ubuntu
    versions:
    - 14.04
    - 16.04

  galaxy_tags:
    - example

dependencies: 
  - geerlingguy.nginx
